### PR TITLE
Fixing circular serialisation issue

### PR DESCRIPTION
**Pull request by matepek**
Fixes: 
- https://github.com/hbenl/vscode-test-explorer-liveshare/issues/4
- https://github.com/matepek/vscode-catch2-test-adapter/issues/209

### CODE REVIEW

**Comment by hbenl** [comment]
So you're proposing to remove all extra properties from the events. I don't want to do that because either it may break some of the adapter's functionality (only in the Live Share guest, but still...) or the adapter doesn't really need the extra properties, in which case it shouldn't send them to Test Explorer in the first place.

**Comment by matepek** [comment]
I think it shouldn't break any of the functionalities. Since the API defines the set of properties, the adapter should comply and provide at least those properties but the Explorer should not depend on any other properties. Therefore removing the properties should not cause any issue. (Even if the property is a getter because copy happens.)

You are right that the adapter doesn't have to proved extra properties but making a copy without the extra properties seem unnecessary.

**Comment by matepek** [comment]
It's not a big stuff, I could change my adapter's code easily. I'm just saying that if this "removal" cause any issue that means that somebody has broken the contract already.

**Comment by hbenl** [comment]
>  if this "removal" cause any issue that means that somebody has broken the contract already.

I kind of agree. Then again, I never said that adding extra properties was forbidden or that any extra properties might be removed. If there's one thing I've learned from maintaining Test Explorer, it's that people will use _all_ the possibilities (intended or not) that an API gives them, often in totally unexpected ways.
That's why I'd prefer this to be fixed in the adapter.

**Comment by matepek** [comment]
It's might just the lack of my javascript knowledge but I don't know any scenario when this can be a problem. We are copying values here just like in the Explorer..  Actually this might would have solved other adapter's similar issues.

**Pull request closed without merging**
